version: "3.8"

services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
            - ./:/var/www/Test-Assignment
        depends_on:
            - php
    mysql:
        image: mysql:8.0
        ports:
            - "3316:3306"
        env_file:
            - mysql.env

    php:
        image: php:8.1-fpm-alpine
        volumes:
            - ./:/var/www/Test-Assignment
        command: /bin/sh -c "docker-php-ext-install mysqli pdo pdo_mysql && php-fpm"

    composer:
        image: composer
        volumes:
            - ./:/var/www/Test-Assignment
        working_dir: /var/www/Test-Assignment
        command: install --ignore-platform-reqs
